
const getters = {
  sidebar: state => state.app.sidebar,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  title: state => state.user.title,
  name: state => state.user.name,
  platimg: state => state.user.platimg,
  ipLocation: state => state.user.ipLocation,
  plattitle: state => state.user.plattitle,
  companyid: state => state.user.companyid,
  permission_routers: state => state.permission.routers,
  addRouters: state => state.permission.addRouters,
  service: state => state.permission.service,
  existBusiness: state => state.permission.existBusiness,
  serviceType: state => state.permission.serviceType,
  businessTrain: state => state.permission.businessTrain,
  businessClass: state => state.permission.businessClass,
  businessOnlineOpenClass: state => state.permission.businessOnlineOpenClass,
  businessAcademicConFerence: state => state.permission.businessAcademicConFerence,
  businessInteractionOpenClass: state => state.permission.businessInteractionOpenClass,
  businessJbktWh: state => state.permission.businessJbktWh,
  userAuths: state => state.permission.userAuths,
  identity: state => state.user.identity,
  videoAudit: state => state.user.videoAudit,
  videoStatistic: state => state.user.videoStatistic,
  caseTitleShow: state => state.user.caseTitleShow,
  caseTitleValue: state => state.user.caseTitleValue,
  questionTitleShow: state => state.user.questionTitleShow,
  questionTitleValue: state => state.user.questionTitleValue,
  cmsStatistic: state => state.user.cmsStatistic,
  themeColor: state => state.user.themeColor,
  companyConfig: state => state.user, // 租户配置信息
}
export default getters
