name: Manual Checkout and Display Code

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Display repository files
      run: |
        echo "Repository files:"
        ls -la
